const HOST_URL = process.env.NEXT_PUBLIC_HOST_URL ?? "";
const HOST_URL_FOR_EXTERNAL_CALL =
  process.env.NEXT_PUBLIC_HOST_URL_FOR_EXTERNAL_CALL ?? "";
const PAGE_SIZE = Number(process.env.NEXT_PUBLIC_PAGE_SIZE) ?? 60;
const ALLOWED_FETCH_MORE_TIME =
  Number(process.env.NEXT_PUBLIC_ALLOWED_FETCH_MORE_TIME) ?? 3;
const BACKEND_URL = process.env.NEXT_PUBLIC_BACKEND_URL;
const FORCED_CLEAR_KEYS =
  process.env.NEXT_PUBLIC_FORCED_CLEAR_KEYS?.split(",") ?? [];

export {
  HOST_URL,
  PAGE_SIZE,
  ALLOWED_FETCH_MORE_TIME,
  BACKEND_URL,
  HOST_URL_FOR_EXTERNAL_CALL,
  FORCED_CLEAR_KEYS,
};
