version: "3.3"
services:
  landing:
    ports:
      - 3006:3000
    build:
      context: .
    env_file:
      - .env.local
    networks:
      - common
networks:
  common:
    external: true
    name: vietsale_default
